set_property SRC_FILE_INFO {cfile:/home/sergo/cms-phase2-muon-trigger/projects/dnn_emtf_displayed/hdl/emtf/ctoc_mmcm_in/ctoc_mmcm_in/ctoc_mmcm_in_in_context.xdc rfile:../../../../hdl/emtf/ctoc_mmcm_in/ctoc_mmcm_in/ctoc_mmcm_in_in_context.xdc id:1 order:EARLY scoped_inst:ctoc/ctoc_mmcm_in_} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sergo/cms-phase2-muon-trigger/projects/dnn_emtf_displayed/hdl/emtf/usrclk_mmcm/usrclk_mmcm/usrclk_mmcm_in_context.xdc rfile:../../../../hdl/emtf/usrclk_mmcm/usrclk_mmcm/usrclk_mmcm_in_context.xdc id:2 order:EARLY scoped_inst:usrclk_mmcm_} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sergo/cms-phase2-muon-trigger/projects/dnn_emtf_displayed/hdl/emtf/ctoc_mmcm/ctoc_mmcm/ctoc_mmcm_in_context.xdc rfile:../../../../hdl/emtf/ctoc_mmcm/ctoc_mmcm/ctoc_mmcm_in_context.xdc id:3 order:EARLY scoped_inst:ctoc/ctoc_mmcm_out} [current_design]
set_property SRC_FILE_INFO {cfile:/home/sergo/cms-phase2-muon-trigger/projects/dnn_emtf_displayed/hdl/emtf/mtf7_core_impl.xdc rfile:../../../../hdl/emtf/mtf7_core_impl.xdc id:4} [current_design]
current_instance ctoc/ctoc_mmcm_in_
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_125M_in] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_125M_in] -edges {1 2 3} -edge_shift {0.000 -3.200 -6.400} [get_ports {}]
current_instance
current_instance usrclk_mmcm_
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports CLK_IN1] -edges {1 2 3} -edge_shift {0.000 -8.125 -16.250} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports CLK_IN1] -edges {1 2 3} -edge_shift {0.000 -7.500 -15.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports CLK_IN1] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports CLK_IN1] -edges {1 2 3} -edge_shift {0.000 -9.375 -18.750} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports CLK_IN1] -edges {1 2 3} -edge_shift {0.000 -11.250 -22.500} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports CLK_IN1] -edges {1 2 3} -edge_shift {0.000 -10.625 -21.250} [get_ports {}]
current_instance
current_instance ctoc/ctoc_mmcm_out
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_125M_in] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_125M_in] -edges {1 2 3} -edge_shift {0.000 -3.200 -6.400} [get_ports {}]
current_instance
set_property src_info {type:XDC file:4 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BA24 IOSTANDARD LVCMOS12} [get_ports m_aresetn]
set_property src_info {type:XDC file:4 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW21} [get_ports core_phase_inc]
set_property src_info {type:XDC file:4 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU21} [get_ports {ext_data_out[13]}]
set_property src_info {type:XDC file:4 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BC23} [get_ports {ext_data_in[13]}]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU25} [get_ports pcie_clk]
set_property src_info {type:XDC file:4 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BA25} [get_ports {ext_data_in[0]}]
set_property src_info {type:XDC file:4 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BB23} [get_ports ext_clk_out]
set_property src_info {type:XDC file:4 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AY24} [get_ports {ext_data_in[1]}]
set_property src_info {type:XDC file:4 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU23} [get_ports {ext_data_in[2]}]
set_property src_info {type:XDC file:4 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU22} [get_ports {ext_data_in[3]}]
set_property src_info {type:XDC file:4 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW25} [get_ports {ext_data_in[4]}]
set_property src_info {type:XDC file:4 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW26} [get_ports {ext_data_in[5]}]
set_property src_info {type:XDC file:4 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BD26} [get_ports {ext_data_in[6]}]
set_property src_info {type:XDC file:4 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BC25} [get_ports {ext_data_in[7]}]
set_property src_info {type:XDC file:4 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AT23} [get_ports {ext_data_in[8]}]
set_property src_info {type:XDC file:4 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW22} [get_ports {ext_data_in[9]}]
set_property src_info {type:XDC file:4 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU26} [get_ports {ext_data_in[10]}]
set_property src_info {type:XDC file:4 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AU27} [get_ports {ext_data_in[11]}]
set_property src_info {type:XDC file:4 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AN23} [get_ports {ext_data_in[12]}]
set_property src_info {type:XDC file:4 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW24} [get_ports {ext_data_out[0]}]
set_property src_info {type:XDC file:4 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AR22} [get_ports {ext_data_out[1]}]
set_property src_info {type:XDC file:4 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AV23} [get_ports {ext_data_out[2]}]
set_property src_info {type:XDC file:4 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BA20} [get_ports {ext_data_out[3]}]
set_property src_info {type:XDC file:4 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BB22} [get_ports {ext_data_out[4]}]
set_property src_info {type:XDC file:4 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AY18} [get_ports {ext_data_out[5]}]
set_property src_info {type:XDC file:4 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW19} [get_ports {ext_data_out[6]}]
set_property src_info {type:XDC file:4 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC BA21} [get_ports {ext_data_out[7]}]
set_property src_info {type:XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AY23} [get_ports {ext_data_out[8]}]
set_property src_info {type:XDC file:4 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AV22} [get_ports {ext_data_out[9]}]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AY19} [get_ports {ext_data_out[10]}]
set_property src_info {type:XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AY21} [get_ports {ext_data_out[11]}]
set_property src_info {type:XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AW20} [get_ports {ext_data_out[12]}]
set_property src_info {type:XDC file:4 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AT21} [get_ports ext_clk_in]
set_property src_info {type:XDC file:4 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {LOC AT8} [get_ports clk40_in_p]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks pcie_clk] -to [get_clocks CLK_OUT1_usrclk_mmcm]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks CLK_OUT1_usrclk_mmcm] -to [get_clocks pcie_clk]
set_property src_info {type:XDC file:4 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks pcie_clk] -to [get_clocks CLK_OUT2_usrclk_mmcm]
set_property src_info {type:XDC file:4 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks CLK_OUT2_usrclk_mmcm] -to [get_clocks pcie_clk]
set_property src_info {type:XDC file:4 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks pcie_clk] -to [get_clocks CLK_OUT4_usrclk_mmcm]
set_property src_info {type:XDC file:4 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_clocks CLK_OUT4_usrclk_mmcm] -to [get_clocks pcie_clk]
