webtalk_init -webtalk_dir /home/sergo/cms-phase2-muon-trigger/projects/dnn_emtf_displayed/top/top.sim/sim_1/synth/func/xsim/xsim.dir/top_tb_func_synth/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 16 21:41:49 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "212432185_1777572229_210763613_044" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9af203d7-6ac7-4942-9f39-39224d875e52" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "6a5e91db9ae84fe7ab347d870930052e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Scientific" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Scientific Linux release 7.9 (Nitrogen)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-7960X CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1200.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "134.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "31" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "29192 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "9279 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "195185" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "33094" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "382.45_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "3860896_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1467276977 -regid "212432185_1777572229_210763613_044" -xml /home/sergo/cms-phase2-muon-trigger/projects/dnn_emtf_displayed/top/top.sim/sim_1/synth/func/xsim/xsim.dir/top_tb_func_synth/webtalk/usage_statistics_ext_xsim.xml -html /home/sergo/cms-phase2-muon-trigger/projects/dnn_emtf_displayed/top/top.sim/sim_1/synth/func/xsim/xsim.dir/top_tb_func_synth/webtalk/usage_statistics_ext_xsim.html -wdm /home/sergo/cms-phase2-muon-trigger/projects/dnn_emtf_displayed/top/top.sim/sim_1/synth/func/xsim/xsim.dir/top_tb_func_synth/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
