-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_latency_0_0_0 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of dense_latency_0_0_0 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv19_2BE91 : STD_LOGIC_VECTOR (18 downto 0) := "0101011111010010001";
    constant ap_const_lv19_6B00C : STD_LOGIC_VECTOR (18 downto 0) := "1101011000000001100";
    constant ap_const_lv19_67142 : STD_LOGIC_VECTOR (18 downto 0) := "1100111000101000010";
    constant ap_const_lv19_63A21 : STD_LOGIC_VECTOR (18 downto 0) := "1100011101000100001";
    constant ap_const_lv19_55A40 : STD_LOGIC_VECTOR (18 downto 0) := "1010101101001000000";
    constant ap_const_lv19_7D842 : STD_LOGIC_VECTOR (18 downto 0) := "1111101100001000010";
    constant ap_const_lv19_55FA2 : STD_LOGIC_VECTOR (18 downto 0) := "1010101111110100010";
    constant ap_const_lv19_62BF5 : STD_LOGIC_VECTOR (18 downto 0) := "1100010101111110101";
    constant ap_const_lv19_77548 : STD_LOGIC_VECTOR (18 downto 0) := "1110111010101001000";
    constant ap_const_lv19_25439 : STD_LOGIC_VECTOR (18 downto 0) := "0100101010000111001";
    constant ap_const_lv19_20482 : STD_LOGIC_VECTOR (18 downto 0) := "0100000010010000010";
    constant ap_const_lv19_51795 : STD_LOGIC_VECTOR (18 downto 0) := "1010001011110010101";
    constant ap_const_lv19_7D9D9 : STD_LOGIC_VECTOR (18 downto 0) := "1111101100111011001";
    constant ap_const_lv19_1C197 : STD_LOGIC_VECTOR (18 downto 0) := "0011100000110010111";
    constant ap_const_lv19_304D4 : STD_LOGIC_VECTOR (18 downto 0) := "0110000010011010100";
    constant ap_const_lv19_C1C2 : STD_LOGIC_VECTOR (18 downto 0) := "0001100000111000010";
    constant ap_const_lv19_66416 : STD_LOGIC_VECTOR (18 downto 0) := "1100110010000010110";
    constant ap_const_lv19_65DDB : STD_LOGIC_VECTOR (18 downto 0) := "1100101110111011011";
    constant ap_const_lv19_13B6 : STD_LOGIC_VECTOR (18 downto 0) := "0000001001110110110";
    constant ap_const_lv19_5A565 : STD_LOGIC_VECTOR (18 downto 0) := "1011010010101100101";
    constant ap_const_lv21_11364 : STD_LOGIC_VECTOR (20 downto 0) := "000010001001101100100";
    constant ap_const_lv21_1FD6D0 : STD_LOGIC_VECTOR (20 downto 0) := "111111101011011010000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";

    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal add_ln703_596_fu_3273_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_596_reg_3461 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_598_fu_3285_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_598_reg_3466 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_600_fu_3297_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_600_reg_3471 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_606_fu_3321_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_606_reg_3476 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_608_fu_3333_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_608_reg_3481 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_610_fu_3345_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_610_reg_3486 : STD_LOGIC_VECTOR (20 downto 0);
    signal grp_product_fu_154_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_154_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call40 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call40 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call40 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call40 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call40 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call40 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp30 : BOOLEAN;
    signal grp_product_fu_155_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_155_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call42 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call42 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call42 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call42 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call42 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call42 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp31 : BOOLEAN;
    signal grp_product_fu_156_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_156_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call34 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call34 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call34 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call34 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call34 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call34 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp27 : BOOLEAN;
    signal grp_product_fu_157_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_157_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call36 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call36 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call36 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call36 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call36 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call36 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp28 : BOOLEAN;
    signal grp_product_fu_158_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_158_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call16 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call16 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call16 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call16 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call16 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call16 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp18 : BOOLEAN;
    signal grp_product_fu_159_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_159_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call38 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call38 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call38 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call38 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call38 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call38 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp29 : BOOLEAN;
    signal grp_product_fu_160_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_160_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call28 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call28 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call28 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call28 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call28 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call28 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp24 : BOOLEAN;
    signal grp_product_fu_161_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_161_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call30 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call30 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call30 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call30 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call30 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call30 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp25 : BOOLEAN;
    signal grp_product_fu_162_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_162_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call46 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call46 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call46 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call46 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call46 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call46 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp33 : BOOLEAN;
    signal grp_product_fu_163_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_163_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call20 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call20 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call20 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call20 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call20 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call20 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp20 : BOOLEAN;
    signal grp_product_fu_164_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_164_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call44 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call44 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call44 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call44 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call44 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call44 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp32 : BOOLEAN;
    signal grp_product_fu_165_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_165_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call48 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call48 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call48 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call48 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call48 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call48 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp34 : BOOLEAN;
    signal grp_product_fu_166_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_166_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call14 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call14 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call14 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call14 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call14 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call14 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp17 : BOOLEAN;
    signal grp_product_fu_167_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_167_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call24 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call24 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call24 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call24 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call24 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call24 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp22 : BOOLEAN;
    signal grp_product_fu_168_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_168_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call32 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call32 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call32 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call32 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call32 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call32 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp26 : BOOLEAN;
    signal grp_product_fu_169_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_169_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call18 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call18 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call18 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call18 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call18 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call18 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp19 : BOOLEAN;
    signal grp_product_fu_170_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_170_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call50 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call50 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call50 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call50 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call50 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call50 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp35 : BOOLEAN;
    signal grp_product_fu_171_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_171_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call22 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call22 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call22 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call22 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call22 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call22 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp21 : BOOLEAN;
    signal grp_product_fu_172_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_172_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call26 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call26 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call26 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call26 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call26 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call26 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp23 : BOOLEAN;
    signal grp_product_fu_173_ap_return : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_product_fu_173_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call52 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call52 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2_ignore_call52 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3_ignore_call52 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4_ignore_call52 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5_ignore_call52 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp36 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal trunc_ln203_2_fu_3183_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_fu_3175_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_8_fu_3207_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_6_fu_3199_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_4_fu_3191_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_594_fu_3261_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_fu_3255_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_595_fu_3267_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_14_fu_3231_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_12_fu_3223_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_10_fu_3215_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_597_fu_3279_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_18_fu_3247_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_16_fu_3239_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_599_fu_3291_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_3_fu_3187_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_1_fu_3179_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_9_fu_3211_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_7_fu_3203_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_5_fu_3195_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_604_fu_3309_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_603_fu_3303_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_605_fu_3315_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_15_fu_3235_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_13_fu_3227_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_11_fu_3219_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_607_fu_3327_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln703_fu_3251_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal trunc_ln203_17_fu_3243_p1 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_609_fu_3339_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_601_fu_3351_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal add_ln703_611_fu_3360_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal p_Val2_s_fu_3355_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal acc_1_V_fu_3364_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal data_0_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_1_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_2_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_3_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_4_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_5_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_6_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_7_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_8_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal data_9_V_read_int_reg : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (11 downto 0);

    component product IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        a_V : IN STD_LOGIC_VECTOR (23 downto 0);
        w_V : IN STD_LOGIC_VECTOR (18 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (23 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_product_fu_154 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_6_V_read_int_reg,
        w_V => ap_const_lv19_2BE91,
        ap_return => grp_product_fu_154_ap_return,
        ap_ce => grp_product_fu_154_ap_ce);

    grp_product_fu_155 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_7_V_read_int_reg,
        w_V => ap_const_lv19_6B00C,
        ap_return => grp_product_fu_155_ap_return,
        ap_ce => grp_product_fu_155_ap_ce);

    grp_product_fu_156 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_5_V_read_int_reg,
        w_V => ap_const_lv19_67142,
        ap_return => grp_product_fu_156_ap_return,
        ap_ce => grp_product_fu_156_ap_ce);

    grp_product_fu_157 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_5_V_read_int_reg,
        w_V => ap_const_lv19_63A21,
        ap_return => grp_product_fu_157_ap_return,
        ap_ce => grp_product_fu_157_ap_ce);

    grp_product_fu_158 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_0_V_read_int_reg,
        w_V => ap_const_lv19_55A40,
        ap_return => grp_product_fu_158_ap_return,
        ap_ce => grp_product_fu_158_ap_ce);

    grp_product_fu_159 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_6_V_read_int_reg,
        w_V => ap_const_lv19_7D842,
        ap_return => grp_product_fu_159_ap_return,
        ap_ce => grp_product_fu_159_ap_ce);

    grp_product_fu_160 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_3_V_read_int_reg,
        w_V => ap_const_lv19_55FA2,
        ap_return => grp_product_fu_160_ap_return,
        ap_ce => grp_product_fu_160_ap_ce);

    grp_product_fu_161 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_4_V_read_int_reg,
        w_V => ap_const_lv19_62BF5,
        ap_return => grp_product_fu_161_ap_return,
        ap_ce => grp_product_fu_161_ap_ce);

    grp_product_fu_162 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_8_V_read_int_reg,
        w_V => ap_const_lv19_77548,
        ap_return => grp_product_fu_162_ap_return,
        ap_ce => grp_product_fu_162_ap_ce);

    grp_product_fu_163 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_1_V_read_int_reg,
        w_V => ap_const_lv19_25439,
        ap_return => grp_product_fu_163_ap_return,
        ap_ce => grp_product_fu_163_ap_ce);

    grp_product_fu_164 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_7_V_read_int_reg,
        w_V => ap_const_lv19_20482,
        ap_return => grp_product_fu_164_ap_return,
        ap_ce => grp_product_fu_164_ap_ce);

    grp_product_fu_165 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_8_V_read_int_reg,
        w_V => ap_const_lv19_51795,
        ap_return => grp_product_fu_165_ap_return,
        ap_ce => grp_product_fu_165_ap_ce);

    grp_product_fu_166 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_0_V_read_int_reg,
        w_V => ap_const_lv19_7D9D9,
        ap_return => grp_product_fu_166_ap_return,
        ap_ce => grp_product_fu_166_ap_ce);

    grp_product_fu_167 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_2_V_read_int_reg,
        w_V => ap_const_lv19_1C197,
        ap_return => grp_product_fu_167_ap_return,
        ap_ce => grp_product_fu_167_ap_ce);

    grp_product_fu_168 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_4_V_read_int_reg,
        w_V => ap_const_lv19_304D4,
        ap_return => grp_product_fu_168_ap_return,
        ap_ce => grp_product_fu_168_ap_ce);

    grp_product_fu_169 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_1_V_read_int_reg,
        w_V => ap_const_lv19_C1C2,
        ap_return => grp_product_fu_169_ap_return,
        ap_ce => grp_product_fu_169_ap_ce);

    grp_product_fu_170 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_9_V_read_int_reg,
        w_V => ap_const_lv19_66416,
        ap_return => grp_product_fu_170_ap_return,
        ap_ce => grp_product_fu_170_ap_ce);

    grp_product_fu_171 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_2_V_read_int_reg,
        w_V => ap_const_lv19_65DDB,
        ap_return => grp_product_fu_171_ap_return,
        ap_ce => grp_product_fu_171_ap_ce);

    grp_product_fu_172 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_3_V_read_int_reg,
        w_V => ap_const_lv19_13B6,
        ap_return => grp_product_fu_172_ap_return,
        ap_ce => grp_product_fu_172_ap_ce);

    grp_product_fu_173 : component product
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        a_V => data_9_V_read_int_reg,
        w_V => ap_const_lv19_5A565,
        ap_return => grp_product_fu_173_ap_return,
        ap_ce => grp_product_fu_173_ap_ce);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln703_596_reg_3461 <= add_ln703_596_fu_3273_p2;
                add_ln703_598_reg_3466 <= add_ln703_598_fu_3285_p2;
                add_ln703_600_reg_3471 <= add_ln703_600_fu_3297_p2;
                add_ln703_606_reg_3476 <= add_ln703_606_fu_3321_p2;
                add_ln703_608_reg_3481 <= add_ln703_608_fu_3333_p2;
                add_ln703_610_reg_3486 <= add_ln703_610_fu_3345_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= p_Val2_s_fu_3355_p2(20 downto 9);
                ap_return_1_int_reg <= acc_1_V_fu_3364_p2(20 downto 9);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                data_0_V_read_int_reg <= data_0_V_read;
                data_1_V_read_int_reg <= data_1_V_read;
                data_2_V_read_int_reg <= data_2_V_read;
                data_3_V_read_int_reg <= data_3_V_read;
                data_4_V_read_int_reg <= data_4_V_read;
                data_5_V_read_int_reg <= data_5_V_read;
                data_6_V_read_int_reg <= data_6_V_read;
                data_7_V_read_int_reg <= data_7_V_read;
                data_8_V_read_int_reg <= data_8_V_read;
                data_9_V_read_int_reg <= data_9_V_read;
            end if;
        end if;
    end process;
    acc_1_V_fu_3364_p2 <= std_logic_vector(unsigned(add_ln703_606_reg_3476) + unsigned(add_ln703_611_fu_3360_p2));
    add_ln703_594_fu_3261_p2 <= std_logic_vector(unsigned(trunc_ln203_8_fu_3207_p1) + unsigned(trunc_ln203_6_fu_3199_p1));
    add_ln703_595_fu_3267_p2 <= std_logic_vector(unsigned(trunc_ln203_4_fu_3191_p1) + unsigned(add_ln703_594_fu_3261_p2));
    add_ln703_596_fu_3273_p2 <= std_logic_vector(unsigned(add_ln703_fu_3255_p2) + unsigned(add_ln703_595_fu_3267_p2));
    add_ln703_597_fu_3279_p2 <= std_logic_vector(unsigned(trunc_ln203_14_fu_3231_p1) + unsigned(trunc_ln203_12_fu_3223_p1));
    add_ln703_598_fu_3285_p2 <= std_logic_vector(unsigned(trunc_ln203_10_fu_3215_p1) + unsigned(add_ln703_597_fu_3279_p2));
    add_ln703_599_fu_3291_p2 <= std_logic_vector(unsigned(ap_const_lv21_11364) + unsigned(trunc_ln203_18_fu_3247_p1));
    add_ln703_600_fu_3297_p2 <= std_logic_vector(unsigned(trunc_ln203_16_fu_3239_p1) + unsigned(add_ln703_599_fu_3291_p2));
    add_ln703_601_fu_3351_p2 <= std_logic_vector(unsigned(add_ln703_598_reg_3466) + unsigned(add_ln703_600_reg_3471));
    add_ln703_603_fu_3303_p2 <= std_logic_vector(unsigned(trunc_ln203_3_fu_3187_p1) + unsigned(trunc_ln203_1_fu_3179_p1));
    add_ln703_604_fu_3309_p2 <= std_logic_vector(unsigned(trunc_ln203_9_fu_3211_p1) + unsigned(trunc_ln203_7_fu_3203_p1));
    add_ln703_605_fu_3315_p2 <= std_logic_vector(unsigned(trunc_ln203_5_fu_3195_p1) + unsigned(add_ln703_604_fu_3309_p2));
    add_ln703_606_fu_3321_p2 <= std_logic_vector(unsigned(add_ln703_603_fu_3303_p2) + unsigned(add_ln703_605_fu_3315_p2));
    add_ln703_607_fu_3327_p2 <= std_logic_vector(unsigned(trunc_ln203_15_fu_3235_p1) + unsigned(trunc_ln203_13_fu_3227_p1));
    add_ln703_608_fu_3333_p2 <= std_logic_vector(unsigned(trunc_ln203_11_fu_3219_p1) + unsigned(add_ln703_607_fu_3327_p2));
    add_ln703_609_fu_3339_p2 <= std_logic_vector(signed(ap_const_lv21_1FD6D0) + signed(trunc_ln703_fu_3251_p1));
    add_ln703_610_fu_3345_p2 <= std_logic_vector(unsigned(trunc_ln203_17_fu_3243_p1) + unsigned(add_ln703_609_fu_3339_p2));
    add_ln703_611_fu_3360_p2 <= std_logic_vector(unsigned(add_ln703_608_reg_3481) + unsigned(add_ln703_610_reg_3486));
    add_ln703_fu_3255_p2 <= std_logic_vector(unsigned(trunc_ln203_2_fu_3183_p1) + unsigned(trunc_ln203_fu_3175_p1));
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp29 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp31 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp35 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001_ignoreCallOp36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call38 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call40 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call42 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call44 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call46 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call48 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call50 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call52 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call38 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call40 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call42 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call44 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call46 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call48 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call50 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call52 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call38 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call40 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call42 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call44 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call46 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call48 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call50 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2_ignore_call52 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call38 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call40 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call42 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call44 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call46 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call48 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call50 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3_ignore_call52 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call38 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call40 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call42 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call44 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call46 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call48 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call50 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4_ignore_call52 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call36 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call38 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call40 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call42 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call44 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call46 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call48 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call50 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5_ignore_call52 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(p_Val2_s_fu_3355_p2, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= p_Val2_s_fu_3355_p2(20 downto 9);
        end if; 
    end process;


    ap_return_1_assign_proc : process(acc_1_V_fu_3364_p2, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= acc_1_V_fu_3364_p2(20 downto 9);
        end if; 
    end process;


    grp_product_fu_154_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp30, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp30))) then 
            grp_product_fu_154_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_154_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_155_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp31, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp31))) then 
            grp_product_fu_155_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_155_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_156_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp27, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp27))) then 
            grp_product_fu_156_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_156_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_157_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp28, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp28))) then 
            grp_product_fu_157_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_157_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_158_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp18, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp18))) then 
            grp_product_fu_158_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_158_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_159_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp29, ap_ce_reg)
    begin
        if (((ap_const_logic_1 = ap_ce_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp29))) then 
            grp_product_fu_159_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_159_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_160_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp24, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp24) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_160_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_160_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_161_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp25, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp25) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_161_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_161_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_162_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp33, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp33) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_162_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_162_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_163_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp20, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp20) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_163_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_163_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_164_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp32, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp32) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_164_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_164_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_165_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp34, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp34) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_165_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_165_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_166_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp17, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp17) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_166_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_166_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_167_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp22, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp22) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_167_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_167_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_168_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp26, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp26) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_168_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_168_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_169_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp19, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp19) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_169_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_169_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_170_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp35, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp35) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_170_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_170_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_171_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp21, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp21) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_171_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_171_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_172_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp23, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp23) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_172_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_172_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_product_fu_173_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001_ignoreCallOp36, ap_ce_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp36) and (ap_const_logic_1 = ap_ce_reg))) then 
            grp_product_fu_173_ap_ce <= ap_const_logic_1;
        else 
            grp_product_fu_173_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    p_Val2_s_fu_3355_p2 <= std_logic_vector(unsigned(add_ln703_596_reg_3461) + unsigned(add_ln703_601_fu_3351_p2));
    trunc_ln203_10_fu_3215_p1 <= grp_product_fu_156_ap_return(21 - 1 downto 0);
    trunc_ln203_11_fu_3219_p1 <= grp_product_fu_157_ap_return(21 - 1 downto 0);
    trunc_ln203_12_fu_3223_p1 <= grp_product_fu_159_ap_return(21 - 1 downto 0);
    trunc_ln203_13_fu_3227_p1 <= grp_product_fu_154_ap_return(21 - 1 downto 0);
    trunc_ln203_14_fu_3231_p1 <= grp_product_fu_155_ap_return(21 - 1 downto 0);
    trunc_ln203_15_fu_3235_p1 <= grp_product_fu_164_ap_return(21 - 1 downto 0);
    trunc_ln203_16_fu_3239_p1 <= grp_product_fu_162_ap_return(21 - 1 downto 0);
    trunc_ln203_17_fu_3243_p1 <= grp_product_fu_165_ap_return(21 - 1 downto 0);
    trunc_ln203_18_fu_3247_p1 <= grp_product_fu_170_ap_return(21 - 1 downto 0);
    trunc_ln203_1_fu_3179_p1 <= grp_product_fu_158_ap_return(21 - 1 downto 0);
    trunc_ln203_2_fu_3183_p1 <= grp_product_fu_169_ap_return(21 - 1 downto 0);
    trunc_ln203_3_fu_3187_p1 <= grp_product_fu_163_ap_return(21 - 1 downto 0);
    trunc_ln203_4_fu_3191_p1 <= grp_product_fu_171_ap_return(21 - 1 downto 0);
    trunc_ln203_5_fu_3195_p1 <= grp_product_fu_167_ap_return(21 - 1 downto 0);
    trunc_ln203_6_fu_3199_p1 <= grp_product_fu_172_ap_return(21 - 1 downto 0);
    trunc_ln203_7_fu_3203_p1 <= grp_product_fu_160_ap_return(21 - 1 downto 0);
    trunc_ln203_8_fu_3207_p1 <= grp_product_fu_161_ap_return(21 - 1 downto 0);
    trunc_ln203_9_fu_3211_p1 <= grp_product_fu_168_ap_return(21 - 1 downto 0);
    trunc_ln203_fu_3175_p1 <= grp_product_fu_166_ap_return(21 - 1 downto 0);
    trunc_ln703_fu_3251_p1 <= grp_product_fu_173_ap_return(21 - 1 downto 0);
end behav;
