-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2019.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity tanh_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_0_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_1_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_2_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_3_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_4_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_5_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_6_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_7_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_8_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    data_9_V_read : IN STD_LOGIC_VECTOR (23 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (23 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of tanh_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv34_3FFFFFFF9 : STD_LOGIC_VECTOR (33 downto 0) := "1111111111111111111111111111111001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv19_1 : STD_LOGIC_VECTOR (18 downto 0) := "0000000000000000001";
    constant ap_const_lv19_200 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001000000000";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv18_200 : STD_LOGIC_VECTOR (17 downto 0) := "000000001000000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tanh_table7_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce0 : STD_LOGIC;
    signal tanh_table7_q0 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce1 : STD_LOGIC;
    signal tanh_table7_q1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce2 : STD_LOGIC;
    signal tanh_table7_q2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce3 : STD_LOGIC;
    signal tanh_table7_q3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address4 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce4 : STD_LOGIC;
    signal tanh_table7_q4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address5 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce5 : STD_LOGIC;
    signal tanh_table7_q5 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address6 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce6 : STD_LOGIC;
    signal tanh_table7_q6 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address7 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce7 : STD_LOGIC;
    signal tanh_table7_q7 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address8 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce8 : STD_LOGIC;
    signal tanh_table7_q8 : STD_LOGIC_VECTOR (10 downto 0);
    signal tanh_table7_address9 : STD_LOGIC_VECTOR (9 downto 0);
    signal tanh_table7_ce9 : STD_LOGIC;
    signal tanh_table7_q9 : STD_LOGIC_VECTOR (10 downto 0);
    signal trunc_ln319_fu_337_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_reg_1749 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_46_reg_1754 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_15_fu_423_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_15_reg_1759 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_49_reg_1764 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_16_fu_509_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_16_reg_1769 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_51_reg_1774 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_17_fu_595_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_17_reg_1779 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_53_reg_1784 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_18_fu_681_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_18_reg_1789 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_55_reg_1794 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_19_fu_767_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_19_reg_1799 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_57_reg_1804 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_20_fu_853_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_20_reg_1809 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_59_reg_1814 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_21_fu_939_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_21_reg_1819 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_61_reg_1824 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_22_fu_1025_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_22_reg_1829 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_63_reg_1834 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln319_23_fu_1111_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln319_23_reg_1839 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_65_reg_1844 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln322_fu_1161_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_reg_1849 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_1_fu_1201_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_1_reg_1854 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_2_fu_1241_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_2_reg_1859 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_3_fu_1281_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_3_reg_1864 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_4_fu_1321_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_4_reg_1869 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_5_fu_1361_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_5_reg_1874 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_6_fu_1401_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_6_reg_1879 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_7_fu_1441_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_7_reg_1884 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_8_fu_1481_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_8_reg_1889 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_9_fu_1521_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln322_9_reg_1894 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal zext_ln323_fu_1529_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_15_fu_1533_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_16_fu_1537_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_17_fu_1541_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_18_fu_1545_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_19_fu_1549_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_20_fu_1553_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_21_fu_1557_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_22_fu_1561_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln323_23_fu_1565_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_fu_277_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln_fu_269_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_fu_297_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_fu_301_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_fu_287_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_fu_309_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_fu_315_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_fu_291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_fu_321_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_fu_329_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_fu_341_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_29_fu_363_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_s_fu_355_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_15_fu_383_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_1_fu_387_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_15_fu_373_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_1_fu_395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_15_fu_401_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_15_fu_377_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_1_fu_407_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_15_fu_415_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_20_fu_427_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_30_fu_449_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_14_fu_441_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_16_fu_469_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_2_fu_473_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_16_fu_459_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_2_fu_481_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_16_fu_487_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_16_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_2_fu_493_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_16_fu_501_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_21_fu_513_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_31_fu_535_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_15_fu_527_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_17_fu_555_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_3_fu_559_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_17_fu_545_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_3_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_17_fu_573_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_17_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_3_fu_579_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_17_fu_587_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_22_fu_599_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_32_fu_621_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_16_fu_613_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_18_fu_641_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_4_fu_645_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_18_fu_631_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_4_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_18_fu_659_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_18_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_4_fu_665_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_18_fu_673_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_23_fu_685_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_33_fu_707_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_17_fu_699_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_19_fu_727_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_5_fu_731_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_19_fu_717_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_5_fu_739_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_19_fu_745_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_19_fu_721_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_5_fu_751_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_19_fu_759_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_24_fu_771_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_34_fu_793_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_18_fu_785_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_20_fu_813_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_6_fu_817_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_20_fu_803_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_6_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_20_fu_831_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_20_fu_807_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_6_fu_837_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_20_fu_845_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_25_fu_857_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_35_fu_879_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_19_fu_871_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_21_fu_899_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_7_fu_903_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_21_fu_889_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_7_fu_911_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_21_fu_917_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_21_fu_893_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_7_fu_923_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_21_fu_931_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_26_fu_943_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_36_fu_965_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_20_fu_957_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_22_fu_985_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_8_fu_989_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_22_fu_975_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_8_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_22_fu_1003_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_22_fu_979_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_8_fu_1009_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_22_fu_1017_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_27_fu_1029_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_37_fu_1051_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal shl_ln1118_21_fu_1043_p3 : STD_LOGIC_VECTOR (33 downto 0);
    signal trunc_ln851_23_fu_1071_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_Result_4_9_fu_1075_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sext_ln850_23_fu_1061_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln851_9_fu_1083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln700_23_fu_1089_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal icmp_ln850_23_fu_1065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln851_9_fu_1095_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal select_ln850_23_fu_1103_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_28_fu_1115_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal add_ln319_30_fu_1129_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_fu_1134_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_48_fu_1145_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_fu_1155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_fu_1141_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_31_fu_1169_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_1_fu_1174_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_50_fu_1185_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_15_fu_1195_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_15_fu_1181_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_32_fu_1209_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_2_fu_1214_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_52_fu_1225_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_16_fu_1235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_16_fu_1221_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_33_fu_1249_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_3_fu_1254_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_54_fu_1265_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_17_fu_1275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_17_fu_1261_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_34_fu_1289_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_4_fu_1294_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_56_fu_1305_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_18_fu_1315_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_18_fu_1301_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_35_fu_1329_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_5_fu_1334_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_58_fu_1345_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_19_fu_1355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_19_fu_1341_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_36_fu_1369_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_6_fu_1374_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_60_fu_1385_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_20_fu_1395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_20_fu_1381_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_37_fu_1409_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_7_fu_1414_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_62_fu_1425_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_21_fu_1435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_21_fu_1421_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_38_fu_1449_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_8_fu_1454_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_64_fu_1465_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_22_fu_1475_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_22_fu_1461_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln319_39_fu_1489_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln321_9_fu_1494_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_66_fu_1505_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln322_23_fu_1515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln321_23_fu_1501_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal res_0_V_write_assig_fu_1569_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_1_V_write_assig_fu_1581_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_2_V_write_assig_fu_1593_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_3_V_write_assig_fu_1605_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_4_V_write_assig_fu_1617_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_5_V_write_assig_fu_1629_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_6_V_write_assig_fu_1641_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_7_V_write_assig_fu_1653_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_8_V_write_assig_fu_1665_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal res_9_V_write_assig_fu_1677_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln728_fu_1577_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_15_fu_1589_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_16_fu_1601_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_17_fu_1613_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_18_fu_1625_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_19_fu_1637_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_20_fu_1649_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_21_fu_1661_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_22_fu_1673_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal sext_ln728_23_fu_1685_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to2 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component tanh_1_tanh_table7 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address2 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address3 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address4 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address5 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address6 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce6 : IN STD_LOGIC;
        q6 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address7 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce7 : IN STD_LOGIC;
        q7 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address8 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce8 : IN STD_LOGIC;
        q8 : OUT STD_LOGIC_VECTOR (10 downto 0);
        address9 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce9 : IN STD_LOGIC;
        q9 : OUT STD_LOGIC_VECTOR (10 downto 0) );
    end component;



begin
    tanh_table7_U : component tanh_1_tanh_table7
    generic map (
        DataWidth => 11,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => tanh_table7_address0,
        ce0 => tanh_table7_ce0,
        q0 => tanh_table7_q0,
        address1 => tanh_table7_address1,
        ce1 => tanh_table7_ce1,
        q1 => tanh_table7_q1,
        address2 => tanh_table7_address2,
        ce2 => tanh_table7_ce2,
        q2 => tanh_table7_q2,
        address3 => tanh_table7_address3,
        ce3 => tanh_table7_ce3,
        q3 => tanh_table7_q3,
        address4 => tanh_table7_address4,
        ce4 => tanh_table7_ce4,
        q4 => tanh_table7_q4,
        address5 => tanh_table7_address5,
        ce5 => tanh_table7_ce5,
        q5 => tanh_table7_q5,
        address6 => tanh_table7_address6,
        ce6 => tanh_table7_ce6,
        q6 => tanh_table7_q6,
        address7 => tanh_table7_address7,
        ce7 => tanh_table7_ce7,
        q7 => tanh_table7_q7,
        address8 => tanh_table7_address8,
        ce8 => tanh_table7_ce8,
        q8 => tanh_table7_q8,
        address9 => tanh_table7_address9,
        ce9 => tanh_table7_ce9,
        q9 => tanh_table7_q9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                select_ln322_1_reg_1854 <= select_ln322_1_fu_1201_p3;
                select_ln322_2_reg_1859 <= select_ln322_2_fu_1241_p3;
                select_ln322_3_reg_1864 <= select_ln322_3_fu_1281_p3;
                select_ln322_4_reg_1869 <= select_ln322_4_fu_1321_p3;
                select_ln322_5_reg_1874 <= select_ln322_5_fu_1361_p3;
                select_ln322_6_reg_1879 <= select_ln322_6_fu_1401_p3;
                select_ln322_7_reg_1884 <= select_ln322_7_fu_1441_p3;
                select_ln322_8_reg_1889 <= select_ln322_8_fu_1481_p3;
                select_ln322_9_reg_1894 <= select_ln322_9_fu_1521_p3;
                select_ln322_reg_1849 <= select_ln322_fu_1161_p3;
                tmp_46_reg_1754 <= add_ln319_fu_341_p2(18 downto 18);
                tmp_49_reg_1764 <= add_ln319_20_fu_427_p2(18 downto 18);
                tmp_51_reg_1774 <= add_ln319_21_fu_513_p2(18 downto 18);
                tmp_53_reg_1784 <= add_ln319_22_fu_599_p2(18 downto 18);
                tmp_55_reg_1794 <= add_ln319_23_fu_685_p2(18 downto 18);
                tmp_57_reg_1804 <= add_ln319_24_fu_771_p2(18 downto 18);
                tmp_59_reg_1814 <= add_ln319_25_fu_857_p2(18 downto 18);
                tmp_61_reg_1824 <= add_ln319_26_fu_943_p2(18 downto 18);
                tmp_63_reg_1834 <= add_ln319_27_fu_1029_p2(18 downto 18);
                tmp_65_reg_1844 <= add_ln319_28_fu_1115_p2(18 downto 18);
                trunc_ln319_15_reg_1759 <= trunc_ln319_15_fu_423_p1;
                trunc_ln319_16_reg_1769 <= trunc_ln319_16_fu_509_p1;
                trunc_ln319_17_reg_1779 <= trunc_ln319_17_fu_595_p1;
                trunc_ln319_18_reg_1789 <= trunc_ln319_18_fu_681_p1;
                trunc_ln319_19_reg_1799 <= trunc_ln319_19_fu_767_p1;
                trunc_ln319_20_reg_1809 <= trunc_ln319_20_fu_853_p1;
                trunc_ln319_21_reg_1819 <= trunc_ln319_21_fu_939_p1;
                trunc_ln319_22_reg_1829 <= trunc_ln319_22_fu_1025_p1;
                trunc_ln319_23_reg_1839 <= trunc_ln319_23_fu_1111_p1;
                trunc_ln319_reg_1749 <= trunc_ln319_fu_337_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln319_20_fu_427_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_15_fu_415_p3));
    add_ln319_21_fu_513_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_16_fu_501_p3));
    add_ln319_22_fu_599_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_17_fu_587_p3));
    add_ln319_23_fu_685_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_18_fu_673_p3));
    add_ln319_24_fu_771_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_19_fu_759_p3));
    add_ln319_25_fu_857_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_20_fu_845_p3));
    add_ln319_26_fu_943_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_21_fu_931_p3));
    add_ln319_27_fu_1029_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_22_fu_1017_p3));
    add_ln319_28_fu_1115_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_23_fu_1103_p3));
    add_ln319_30_fu_1129_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_reg_1749));
    add_ln319_31_fu_1169_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_15_reg_1759));
    add_ln319_32_fu_1209_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_16_reg_1769));
    add_ln319_33_fu_1249_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_17_reg_1779));
    add_ln319_34_fu_1289_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_18_reg_1789));
    add_ln319_35_fu_1329_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_19_reg_1799));
    add_ln319_36_fu_1369_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_20_reg_1809));
    add_ln319_37_fu_1409_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_21_reg_1819));
    add_ln319_38_fu_1449_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_22_reg_1829));
    add_ln319_39_fu_1489_p2 <= std_logic_vector(unsigned(ap_const_lv18_200) + unsigned(trunc_ln319_23_reg_1839));
    add_ln319_fu_341_p2 <= std_logic_vector(unsigned(ap_const_lv19_200) + unsigned(select_ln850_fu_329_p3));
    add_ln700_15_fu_401_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_15_fu_373_p1));
    add_ln700_16_fu_487_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_16_fu_459_p1));
    add_ln700_17_fu_573_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_17_fu_545_p1));
    add_ln700_18_fu_659_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_18_fu_631_p1));
    add_ln700_19_fu_745_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_19_fu_717_p1));
    add_ln700_20_fu_831_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_20_fu_803_p1));
    add_ln700_21_fu_917_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_21_fu_889_p1));
    add_ln700_22_fu_1003_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_22_fu_975_p1));
    add_ln700_23_fu_1089_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_23_fu_1061_p1));
    add_ln700_fu_315_p2 <= std_logic_vector(unsigned(ap_const_lv19_1) + unsigned(sext_ln850_fu_287_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_start = ap_const_logic_0) and (ap_start = ap_const_logic_1));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start = ap_const_logic_0);
    end process;

        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to2_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0_0to2 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to2)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to2 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= sext_ln728_fu_1577_p1;
    ap_return_1 <= sext_ln728_15_fu_1589_p1;
    ap_return_2 <= sext_ln728_16_fu_1601_p1;
    ap_return_3 <= sext_ln728_17_fu_1613_p1;
    ap_return_4 <= sext_ln728_18_fu_1625_p1;
    ap_return_5 <= sext_ln728_19_fu_1637_p1;
    ap_return_6 <= sext_ln728_20_fu_1649_p1;
    ap_return_7 <= sext_ln728_21_fu_1661_p1;
    ap_return_8 <= sext_ln728_22_fu_1673_p1;
    ap_return_9 <= sext_ln728_23_fu_1685_p1;
    icmp_ln322_15_fu_1195_p2 <= "0" when (tmp_50_fu_1185_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_16_fu_1235_p2 <= "0" when (tmp_52_fu_1225_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_17_fu_1275_p2 <= "0" when (tmp_54_fu_1265_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_18_fu_1315_p2 <= "0" when (tmp_56_fu_1305_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_19_fu_1355_p2 <= "0" when (tmp_58_fu_1345_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_20_fu_1395_p2 <= "0" when (tmp_60_fu_1385_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_21_fu_1435_p2 <= "0" when (tmp_62_fu_1425_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_22_fu_1475_p2 <= "0" when (tmp_64_fu_1465_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_23_fu_1515_p2 <= "0" when (tmp_66_fu_1505_p4 = ap_const_lv8_0) else "1";
    icmp_ln322_fu_1155_p2 <= "0" when (tmp_48_fu_1145_p4 = ap_const_lv8_0) else "1";
    icmp_ln850_15_fu_377_p2 <= "1" when (signed(shl_ln1118_s_fu_355_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_16_fu_463_p2 <= "1" when (signed(shl_ln1118_14_fu_441_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_17_fu_549_p2 <= "1" when (signed(shl_ln1118_15_fu_527_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_18_fu_635_p2 <= "1" when (signed(shl_ln1118_16_fu_613_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_19_fu_721_p2 <= "1" when (signed(shl_ln1118_17_fu_699_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_20_fu_807_p2 <= "1" when (signed(shl_ln1118_18_fu_785_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_21_fu_893_p2 <= "1" when (signed(shl_ln1118_19_fu_871_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_22_fu_979_p2 <= "1" when (signed(shl_ln1118_20_fu_957_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_23_fu_1065_p2 <= "1" when (signed(shl_ln1118_21_fu_1043_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln850_fu_291_p2 <= "1" when (signed(shl_ln_fu_269_p3) < signed(ap_const_lv34_3FFFFFFF9)) else "0";
    icmp_ln851_1_fu_395_p2 <= "1" when (p_Result_4_1_fu_387_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_2_fu_481_p2 <= "1" when (p_Result_4_2_fu_473_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_3_fu_567_p2 <= "1" when (p_Result_4_3_fu_559_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_4_fu_653_p2 <= "1" when (p_Result_4_4_fu_645_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_5_fu_739_p2 <= "1" when (p_Result_4_5_fu_731_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_6_fu_825_p2 <= "1" when (p_Result_4_6_fu_817_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_7_fu_911_p2 <= "1" when (p_Result_4_7_fu_903_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_8_fu_997_p2 <= "1" when (p_Result_4_8_fu_989_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_9_fu_1083_p2 <= "1" when (p_Result_4_9_fu_1075_p3 = ap_const_lv13_0) else "0";
    icmp_ln851_fu_309_p2 <= "1" when (p_Result_4_fu_301_p3 = ap_const_lv13_0) else "0";
    p_Result_4_1_fu_387_p3 <= (trunc_ln851_15_fu_383_p1 & ap_const_lv7_0);
    p_Result_4_2_fu_473_p3 <= (trunc_ln851_16_fu_469_p1 & ap_const_lv7_0);
    p_Result_4_3_fu_559_p3 <= (trunc_ln851_17_fu_555_p1 & ap_const_lv7_0);
    p_Result_4_4_fu_645_p3 <= (trunc_ln851_18_fu_641_p1 & ap_const_lv7_0);
    p_Result_4_5_fu_731_p3 <= (trunc_ln851_19_fu_727_p1 & ap_const_lv7_0);
    p_Result_4_6_fu_817_p3 <= (trunc_ln851_20_fu_813_p1 & ap_const_lv7_0);
    p_Result_4_7_fu_903_p3 <= (trunc_ln851_21_fu_899_p1 & ap_const_lv7_0);
    p_Result_4_8_fu_989_p3 <= (trunc_ln851_22_fu_985_p1 & ap_const_lv7_0);
    p_Result_4_9_fu_1075_p3 <= (trunc_ln851_23_fu_1071_p1 & ap_const_lv7_0);
    p_Result_4_fu_301_p3 <= (trunc_ln851_fu_297_p1 & ap_const_lv7_0);
    res_0_V_write_assig_fu_1569_p3 <= (tanh_table7_q0 & ap_const_lv3_0);
    res_1_V_write_assig_fu_1581_p3 <= (tanh_table7_q1 & ap_const_lv3_0);
    res_2_V_write_assig_fu_1593_p3 <= (tanh_table7_q2 & ap_const_lv3_0);
    res_3_V_write_assig_fu_1605_p3 <= (tanh_table7_q3 & ap_const_lv3_0);
    res_4_V_write_assig_fu_1617_p3 <= (tanh_table7_q4 & ap_const_lv3_0);
    res_5_V_write_assig_fu_1629_p3 <= (tanh_table7_q5 & ap_const_lv3_0);
    res_6_V_write_assig_fu_1641_p3 <= (tanh_table7_q6 & ap_const_lv3_0);
    res_7_V_write_assig_fu_1653_p3 <= (tanh_table7_q7 & ap_const_lv3_0);
    res_8_V_write_assig_fu_1665_p3 <= (tanh_table7_q8 & ap_const_lv3_0);
    res_9_V_write_assig_fu_1677_p3 <= (tanh_table7_q9 & ap_const_lv3_0);
    select_ln321_1_fu_1174_p3 <= 
        ap_const_lv18_0 when (tmp_49_reg_1764(0) = '1') else 
        add_ln319_31_fu_1169_p2;
    select_ln321_2_fu_1214_p3 <= 
        ap_const_lv18_0 when (tmp_51_reg_1774(0) = '1') else 
        add_ln319_32_fu_1209_p2;
    select_ln321_3_fu_1254_p3 <= 
        ap_const_lv18_0 when (tmp_53_reg_1784(0) = '1') else 
        add_ln319_33_fu_1249_p2;
    select_ln321_4_fu_1294_p3 <= 
        ap_const_lv18_0 when (tmp_55_reg_1794(0) = '1') else 
        add_ln319_34_fu_1289_p2;
    select_ln321_5_fu_1334_p3 <= 
        ap_const_lv18_0 when (tmp_57_reg_1804(0) = '1') else 
        add_ln319_35_fu_1329_p2;
    select_ln321_6_fu_1374_p3 <= 
        ap_const_lv18_0 when (tmp_59_reg_1814(0) = '1') else 
        add_ln319_36_fu_1369_p2;
    select_ln321_7_fu_1414_p3 <= 
        ap_const_lv18_0 when (tmp_61_reg_1824(0) = '1') else 
        add_ln319_37_fu_1409_p2;
    select_ln321_8_fu_1454_p3 <= 
        ap_const_lv18_0 when (tmp_63_reg_1834(0) = '1') else 
        add_ln319_38_fu_1449_p2;
    select_ln321_9_fu_1494_p3 <= 
        ap_const_lv18_0 when (tmp_65_reg_1844(0) = '1') else 
        add_ln319_39_fu_1489_p2;
    select_ln321_fu_1134_p3 <= 
        ap_const_lv18_0 when (tmp_46_reg_1754(0) = '1') else 
        add_ln319_30_fu_1129_p2;
    select_ln322_1_fu_1201_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_15_fu_1195_p2(0) = '1') else 
        trunc_ln321_15_fu_1181_p1;
    select_ln322_2_fu_1241_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_16_fu_1235_p2(0) = '1') else 
        trunc_ln321_16_fu_1221_p1;
    select_ln322_3_fu_1281_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_17_fu_1275_p2(0) = '1') else 
        trunc_ln321_17_fu_1261_p1;
    select_ln322_4_fu_1321_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_18_fu_1315_p2(0) = '1') else 
        trunc_ln321_18_fu_1301_p1;
    select_ln322_5_fu_1361_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_19_fu_1355_p2(0) = '1') else 
        trunc_ln321_19_fu_1341_p1;
    select_ln322_6_fu_1401_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_20_fu_1395_p2(0) = '1') else 
        trunc_ln321_20_fu_1381_p1;
    select_ln322_7_fu_1441_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_21_fu_1435_p2(0) = '1') else 
        trunc_ln321_21_fu_1421_p1;
    select_ln322_8_fu_1481_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_22_fu_1475_p2(0) = '1') else 
        trunc_ln321_22_fu_1461_p1;
    select_ln322_9_fu_1521_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_23_fu_1515_p2(0) = '1') else 
        trunc_ln321_23_fu_1501_p1;
    select_ln322_fu_1161_p3 <= 
        ap_const_lv10_3FF when (icmp_ln322_fu_1155_p2(0) = '1') else 
        trunc_ln321_fu_1141_p1;
    select_ln850_15_fu_415_p3 <= 
        select_ln851_1_fu_407_p3 when (icmp_ln850_15_fu_377_p2(0) = '1') else 
        sext_ln850_15_fu_373_p1;
    select_ln850_16_fu_501_p3 <= 
        select_ln851_2_fu_493_p3 when (icmp_ln850_16_fu_463_p2(0) = '1') else 
        sext_ln850_16_fu_459_p1;
    select_ln850_17_fu_587_p3 <= 
        select_ln851_3_fu_579_p3 when (icmp_ln850_17_fu_549_p2(0) = '1') else 
        sext_ln850_17_fu_545_p1;
    select_ln850_18_fu_673_p3 <= 
        select_ln851_4_fu_665_p3 when (icmp_ln850_18_fu_635_p2(0) = '1') else 
        sext_ln850_18_fu_631_p1;
    select_ln850_19_fu_759_p3 <= 
        select_ln851_5_fu_751_p3 when (icmp_ln850_19_fu_721_p2(0) = '1') else 
        sext_ln850_19_fu_717_p1;
    select_ln850_20_fu_845_p3 <= 
        select_ln851_6_fu_837_p3 when (icmp_ln850_20_fu_807_p2(0) = '1') else 
        sext_ln850_20_fu_803_p1;
    select_ln850_21_fu_931_p3 <= 
        select_ln851_7_fu_923_p3 when (icmp_ln850_21_fu_893_p2(0) = '1') else 
        sext_ln850_21_fu_889_p1;
    select_ln850_22_fu_1017_p3 <= 
        select_ln851_8_fu_1009_p3 when (icmp_ln850_22_fu_979_p2(0) = '1') else 
        sext_ln850_22_fu_975_p1;
    select_ln850_23_fu_1103_p3 <= 
        select_ln851_9_fu_1095_p3 when (icmp_ln850_23_fu_1065_p2(0) = '1') else 
        sext_ln850_23_fu_1061_p1;
    select_ln850_fu_329_p3 <= 
        select_ln851_fu_321_p3 when (icmp_ln850_fu_291_p2(0) = '1') else 
        sext_ln850_fu_287_p1;
    select_ln851_1_fu_407_p3 <= 
        sext_ln850_15_fu_373_p1 when (icmp_ln851_1_fu_395_p2(0) = '1') else 
        add_ln700_15_fu_401_p2;
    select_ln851_2_fu_493_p3 <= 
        sext_ln850_16_fu_459_p1 when (icmp_ln851_2_fu_481_p2(0) = '1') else 
        add_ln700_16_fu_487_p2;
    select_ln851_3_fu_579_p3 <= 
        sext_ln850_17_fu_545_p1 when (icmp_ln851_3_fu_567_p2(0) = '1') else 
        add_ln700_17_fu_573_p2;
    select_ln851_4_fu_665_p3 <= 
        sext_ln850_18_fu_631_p1 when (icmp_ln851_4_fu_653_p2(0) = '1') else 
        add_ln700_18_fu_659_p2;
    select_ln851_5_fu_751_p3 <= 
        sext_ln850_19_fu_717_p1 when (icmp_ln851_5_fu_739_p2(0) = '1') else 
        add_ln700_19_fu_745_p2;
    select_ln851_6_fu_837_p3 <= 
        sext_ln850_20_fu_803_p1 when (icmp_ln851_6_fu_825_p2(0) = '1') else 
        add_ln700_20_fu_831_p2;
    select_ln851_7_fu_923_p3 <= 
        sext_ln850_21_fu_889_p1 when (icmp_ln851_7_fu_911_p2(0) = '1') else 
        add_ln700_21_fu_917_p2;
    select_ln851_8_fu_1009_p3 <= 
        sext_ln850_22_fu_975_p1 when (icmp_ln851_8_fu_997_p2(0) = '1') else 
        add_ln700_22_fu_1003_p2;
    select_ln851_9_fu_1095_p3 <= 
        sext_ln850_23_fu_1061_p1 when (icmp_ln851_9_fu_1083_p2(0) = '1') else 
        add_ln700_23_fu_1089_p2;
    select_ln851_fu_321_p3 <= 
        sext_ln850_fu_287_p1 when (icmp_ln851_fu_309_p2(0) = '1') else 
        add_ln700_fu_315_p2;
        sext_ln728_15_fu_1589_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_1_V_write_assig_fu_1581_p3),24));

        sext_ln728_16_fu_1601_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_2_V_write_assig_fu_1593_p3),24));

        sext_ln728_17_fu_1613_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_3_V_write_assig_fu_1605_p3),24));

        sext_ln728_18_fu_1625_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_4_V_write_assig_fu_1617_p3),24));

        sext_ln728_19_fu_1637_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_5_V_write_assig_fu_1629_p3),24));

        sext_ln728_20_fu_1649_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_6_V_write_assig_fu_1641_p3),24));

        sext_ln728_21_fu_1661_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_7_V_write_assig_fu_1653_p3),24));

        sext_ln728_22_fu_1673_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_8_V_write_assig_fu_1665_p3),24));

        sext_ln728_23_fu_1685_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_9_V_write_assig_fu_1677_p3),24));

        sext_ln728_fu_1577_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(res_0_V_write_assig_fu_1569_p3),24));

        sext_ln850_15_fu_373_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_29_fu_363_p4),19));

        sext_ln850_16_fu_459_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_30_fu_449_p4),19));

        sext_ln850_17_fu_545_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_31_fu_535_p4),19));

        sext_ln850_18_fu_631_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_32_fu_621_p4),19));

        sext_ln850_19_fu_717_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_33_fu_707_p4),19));

        sext_ln850_20_fu_803_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_34_fu_793_p4),19));

        sext_ln850_21_fu_889_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_35_fu_879_p4),19));

        sext_ln850_22_fu_975_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_36_fu_965_p4),19));

        sext_ln850_23_fu_1061_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_37_fu_1051_p4),19));

        sext_ln850_fu_287_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_s_fu_277_p4),19));

    shl_ln1118_14_fu_441_p3 <= (data_2_V_read & ap_const_lv10_0);
    shl_ln1118_15_fu_527_p3 <= (data_3_V_read & ap_const_lv10_0);
    shl_ln1118_16_fu_613_p3 <= (data_4_V_read & ap_const_lv10_0);
    shl_ln1118_17_fu_699_p3 <= (data_5_V_read & ap_const_lv10_0);
    shl_ln1118_18_fu_785_p3 <= (data_6_V_read & ap_const_lv10_0);
    shl_ln1118_19_fu_871_p3 <= (data_7_V_read & ap_const_lv10_0);
    shl_ln1118_20_fu_957_p3 <= (data_8_V_read & ap_const_lv10_0);
    shl_ln1118_21_fu_1043_p3 <= (data_9_V_read & ap_const_lv10_0);
    shl_ln1118_s_fu_355_p3 <= (data_1_V_read & ap_const_lv10_0);
    shl_ln_fu_269_p3 <= (data_0_V_read & ap_const_lv10_0);
    tanh_table7_address0 <= zext_ln323_fu_1529_p1(10 - 1 downto 0);
    tanh_table7_address1 <= zext_ln323_15_fu_1533_p1(10 - 1 downto 0);
    tanh_table7_address2 <= zext_ln323_16_fu_1537_p1(10 - 1 downto 0);
    tanh_table7_address3 <= zext_ln323_17_fu_1541_p1(10 - 1 downto 0);
    tanh_table7_address4 <= zext_ln323_18_fu_1545_p1(10 - 1 downto 0);
    tanh_table7_address5 <= zext_ln323_19_fu_1549_p1(10 - 1 downto 0);
    tanh_table7_address6 <= zext_ln323_20_fu_1553_p1(10 - 1 downto 0);
    tanh_table7_address7 <= zext_ln323_21_fu_1557_p1(10 - 1 downto 0);
    tanh_table7_address8 <= zext_ln323_22_fu_1561_p1(10 - 1 downto 0);
    tanh_table7_address9 <= zext_ln323_23_fu_1565_p1(10 - 1 downto 0);

    tanh_table7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce0 <= ap_const_logic_1;
        else 
            tanh_table7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce1 <= ap_const_logic_1;
        else 
            tanh_table7_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce2_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce2 <= ap_const_logic_1;
        else 
            tanh_table7_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce3_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce3 <= ap_const_logic_1;
        else 
            tanh_table7_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce4 <= ap_const_logic_1;
        else 
            tanh_table7_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce5_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce5 <= ap_const_logic_1;
        else 
            tanh_table7_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce6_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce6 <= ap_const_logic_1;
        else 
            tanh_table7_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce7_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce7 <= ap_const_logic_1;
        else 
            tanh_table7_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce8_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce8 <= ap_const_logic_1;
        else 
            tanh_table7_ce8 <= ap_const_logic_0;
        end if; 
    end process;


    tanh_table7_ce9_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            tanh_table7_ce9 <= ap_const_logic_1;
        else 
            tanh_table7_ce9 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_29_fu_363_p4 <= data_1_V_read(23 downto 6);
    tmp_30_fu_449_p4 <= data_2_V_read(23 downto 6);
    tmp_31_fu_535_p4 <= data_3_V_read(23 downto 6);
    tmp_32_fu_621_p4 <= data_4_V_read(23 downto 6);
    tmp_33_fu_707_p4 <= data_5_V_read(23 downto 6);
    tmp_34_fu_793_p4 <= data_6_V_read(23 downto 6);
    tmp_35_fu_879_p4 <= data_7_V_read(23 downto 6);
    tmp_36_fu_965_p4 <= data_8_V_read(23 downto 6);
    tmp_37_fu_1051_p4 <= data_9_V_read(23 downto 6);
    tmp_48_fu_1145_p4 <= select_ln321_fu_1134_p3(17 downto 10);
    tmp_50_fu_1185_p4 <= select_ln321_1_fu_1174_p3(17 downto 10);
    tmp_52_fu_1225_p4 <= select_ln321_2_fu_1214_p3(17 downto 10);
    tmp_54_fu_1265_p4 <= select_ln321_3_fu_1254_p3(17 downto 10);
    tmp_56_fu_1305_p4 <= select_ln321_4_fu_1294_p3(17 downto 10);
    tmp_58_fu_1345_p4 <= select_ln321_5_fu_1334_p3(17 downto 10);
    tmp_60_fu_1385_p4 <= select_ln321_6_fu_1374_p3(17 downto 10);
    tmp_62_fu_1425_p4 <= select_ln321_7_fu_1414_p3(17 downto 10);
    tmp_64_fu_1465_p4 <= select_ln321_8_fu_1454_p3(17 downto 10);
    tmp_66_fu_1505_p4 <= select_ln321_9_fu_1494_p3(17 downto 10);
    tmp_s_fu_277_p4 <= data_0_V_read(23 downto 6);
    trunc_ln319_15_fu_423_p1 <= select_ln850_15_fu_415_p3(18 - 1 downto 0);
    trunc_ln319_16_fu_509_p1 <= select_ln850_16_fu_501_p3(18 - 1 downto 0);
    trunc_ln319_17_fu_595_p1 <= select_ln850_17_fu_587_p3(18 - 1 downto 0);
    trunc_ln319_18_fu_681_p1 <= select_ln850_18_fu_673_p3(18 - 1 downto 0);
    trunc_ln319_19_fu_767_p1 <= select_ln850_19_fu_759_p3(18 - 1 downto 0);
    trunc_ln319_20_fu_853_p1 <= select_ln850_20_fu_845_p3(18 - 1 downto 0);
    trunc_ln319_21_fu_939_p1 <= select_ln850_21_fu_931_p3(18 - 1 downto 0);
    trunc_ln319_22_fu_1025_p1 <= select_ln850_22_fu_1017_p3(18 - 1 downto 0);
    trunc_ln319_23_fu_1111_p1 <= select_ln850_23_fu_1103_p3(18 - 1 downto 0);
    trunc_ln319_fu_337_p1 <= select_ln850_fu_329_p3(18 - 1 downto 0);
    trunc_ln321_15_fu_1181_p1 <= select_ln321_1_fu_1174_p3(10 - 1 downto 0);
    trunc_ln321_16_fu_1221_p1 <= select_ln321_2_fu_1214_p3(10 - 1 downto 0);
    trunc_ln321_17_fu_1261_p1 <= select_ln321_3_fu_1254_p3(10 - 1 downto 0);
    trunc_ln321_18_fu_1301_p1 <= select_ln321_4_fu_1294_p3(10 - 1 downto 0);
    trunc_ln321_19_fu_1341_p1 <= select_ln321_5_fu_1334_p3(10 - 1 downto 0);
    trunc_ln321_20_fu_1381_p1 <= select_ln321_6_fu_1374_p3(10 - 1 downto 0);
    trunc_ln321_21_fu_1421_p1 <= select_ln321_7_fu_1414_p3(10 - 1 downto 0);
    trunc_ln321_22_fu_1461_p1 <= select_ln321_8_fu_1454_p3(10 - 1 downto 0);
    trunc_ln321_23_fu_1501_p1 <= select_ln321_9_fu_1494_p3(10 - 1 downto 0);
    trunc_ln321_fu_1141_p1 <= select_ln321_fu_1134_p3(10 - 1 downto 0);
    trunc_ln851_15_fu_383_p1 <= data_1_V_read(6 - 1 downto 0);
    trunc_ln851_16_fu_469_p1 <= data_2_V_read(6 - 1 downto 0);
    trunc_ln851_17_fu_555_p1 <= data_3_V_read(6 - 1 downto 0);
    trunc_ln851_18_fu_641_p1 <= data_4_V_read(6 - 1 downto 0);
    trunc_ln851_19_fu_727_p1 <= data_5_V_read(6 - 1 downto 0);
    trunc_ln851_20_fu_813_p1 <= data_6_V_read(6 - 1 downto 0);
    trunc_ln851_21_fu_899_p1 <= data_7_V_read(6 - 1 downto 0);
    trunc_ln851_22_fu_985_p1 <= data_8_V_read(6 - 1 downto 0);
    trunc_ln851_23_fu_1071_p1 <= data_9_V_read(6 - 1 downto 0);
    trunc_ln851_fu_297_p1 <= data_0_V_read(6 - 1 downto 0);
    zext_ln323_15_fu_1533_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_1_reg_1854),64));
    zext_ln323_16_fu_1537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_2_reg_1859),64));
    zext_ln323_17_fu_1541_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_3_reg_1864),64));
    zext_ln323_18_fu_1545_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_4_reg_1869),64));
    zext_ln323_19_fu_1549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_5_reg_1874),64));
    zext_ln323_20_fu_1553_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_6_reg_1879),64));
    zext_ln323_21_fu_1557_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_7_reg_1884),64));
    zext_ln323_22_fu_1561_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_8_reg_1889),64));
    zext_ln323_23_fu_1565_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_9_reg_1894),64));
    zext_ln323_fu_1529_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln322_reg_1849),64));
end behav;
